# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the article', max_length=60, verbose_name='Akole Iroyin')),
                ('article', models.TextField(help_text='Type the content of your article here', max_length=1000, verbose_name='Oro Iroyin')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(related_name='written_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Iroyin',
                'verbose_name_plural': 'Iroyin',
            },
        ),
    ]
