# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the article', max_length=60, verbose_name='Akole Iroyin')),
                ('content', models.TextField(help_text='Type the content of your article here', max_length=1000, null=True, verbose_name='Oro Iroyin')),
                ('Slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('category', models.CharField(choices=[('oselu', 'Oselu'), ('gbogbogbo', 'Gbogbogbo'), ('owo', 'Owo')], max_length=30, verbose_name='Ipele')),
                ('author', models.ManyToManyField(related_name='written_by', to=settings.AUTH_USER_MODEL, verbose_name='Author(s)')),
            ],
            options={
                'verbose_name_plural': 'Iroyin',
                'verbose_name': 'Iroyin',
            },
        ),
    ]
