# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_auto_20160911_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='article',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='written_by', to=settings.AUTH_USER_MODEL, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('oselu', 'Oselu'), ('gbogbogbo', 'Gbogbogbo')], max_length=30, verbose_name='Ipele'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
